# required to get an OSX environment
language: objective-c

before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"

  # Get hold of ANT.
  - brew update
  - brew install ant
  - brew install caskroom/cask/brew-cask
  - brew cask install flash-player-debugger
  - brew install android-sdk

  # Grab SDK
  - mkdir -p air_sdk
  - wget -O AIRSDK_Compiler.tbz2 http://airdownload.adobe.com/air/mac/download/latest/AIRSDK_Compiler.tbz2
  - tar -xjf AIRSDK_Compiler.tbz2 -C air_sdk
  - mkdir -p air_sdk/frameworks/libs/player/11.1/
  - wget -O playerglobal.swc http://download.macromedia.com/get/flashplayer/updaters/17/playerglobal17_0.swc
  - cp -f playerglobal.swc air_sdk/frameworks/libs/player/11.1/
  - export FLEX_HOME="$TRAVIS_BUILD_DIR/air_sdk"

script: ant -DIGNORE_MOBILE_TARGET=true